//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ForumResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ForumResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ForumResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add posts.
        /// </summary>
        internal static string AddPosts {
            get {
                return ResourceManager.GetString("AddPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add thread.
        /// </summary>
        internal static string AddThread {
            get {
                return ResourceManager.GetString("AddThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation done successfully.
        /// </summary>
        internal static string AddUserSuccessfully {
            get {
                return ResourceManager.GetString("AddUserSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        internal static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banned.
        /// </summary>
        internal static string Banned {
            get {
                return ResourceManager.GetString("Banned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date.
        /// </summary>
        internal static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string btnExit {
            get {
                return ResourceManager.GetString("btnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string btnReset {
            get {
                return ResourceManager.GetString("btnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string btnUpdate {
            get {
                return ResourceManager.GetString("btnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change image.
        /// </summary>
        internal static string ChangeImage {
            get {
                return ResourceManager.GetString("ChangeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        internal static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date.
        /// </summary>
        internal static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisApproved.
        /// </summary>
        internal static string DisApproved {
            get {
                return ResourceManager.GetString("DisApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during the process.
        /// </summary>
        internal static string ErrorUsernotfound {
            get {
                return ResourceManager.GetString("ErrorUsernotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum.
        /// </summary>
        internal static string Forum {
            get {
                return ResourceManager.GetString("Forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum group.
        /// </summary>
        internal static string ForumGroup {
            get {
                return ResourceManager.GetString("ForumGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum group manager.
        /// </summary>
        internal static string ForumGroupManager {
            get {
                return ResourceManager.GetString("ForumGroupManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum manager.
        /// </summary>
        internal static string ForumManager {
            get {
                return ResourceManager.GetString("ForumManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum post manager.
        /// </summary>
        internal static string ForumPostManager {
            get {
                return ResourceManager.GetString("ForumPostManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum posts.
        /// </summary>
        internal static string ForumPosts {
            get {
                return ResourceManager.GetString("ForumPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum thread.
        /// </summary>
        internal static string ForumThread {
            get {
                return ResourceManager.GetString("ForumThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum thread manager.
        /// </summary>
        internal static string ForumThreadManager {
            get {
                return ResourceManager.GetString("ForumThreadManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum user.
        /// </summary>
        internal static string ForumUser {
            get {
                return ResourceManager.GetString("ForumUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum user manager.
        /// </summary>
        internal static string ForumUserManager {
            get {
                return ResourceManager.GetString("ForumUserManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string GroupTitle {
            get {
                return ResourceManager.GetString("GroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string ibtnadd {
            get {
                return ResourceManager.GetString("ibtnadd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ibtnDelete {
            get {
                return ResourceManager.GetString("ibtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InActive.
        /// </summary>
        internal static string InActive {
            get {
                return ResourceManager.GetString("InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is active.
        /// </summary>
        internal static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is banned.
        /// </summary>
        internal static string IsBanned {
            get {
                return ResourceManager.GetString("IsBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is trusted.
        /// </summary>
        internal static string IsTrusted {
            get {
                return ResourceManager.GetString("IsTrusted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join date.
        /// </summary>
        internal static string JoinDate {
            get {
                return ResourceManager.GetString("JoinDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword.
        /// </summary>
        internal static string Keyword {
            get {
                return ResourceManager.GetString("Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last thread.
        /// </summary>
        internal static string LastThread {
            get {
                return ResourceManager.GetString("LastThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added by:.
        /// </summary>
        internal static string lblAddedby {
            get {
                return ResourceManager.GetString("lblAddedby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Post.
        /// </summary>
        internal static string lblAddpost {
            get {
                return ResourceManager.GetString("lblAddpost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string lblChangePassword {
            get {
                return ResourceManager.GetString("lblChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        internal static string lblForumUserPrfilePages {
            get {
                return ResourceManager.GetString("lblForumUserPrfilePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string lblLogut {
            get {
                return ResourceManager.GetString("lblLogut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participation Count:.
        /// </summary>
        internal static string lblParticipationcount {
            get {
                return ResourceManager.GetString("lblParticipationcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register New User.
        /// </summary>
        internal static string lblRegisterUsersForums {
            get {
                return ResourceManager.GetString("lblRegisterUsersForums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Security Information.
        /// </summary>
        internal static string lblSecurityInformarion {
            get {
                return ResourceManager.GetString("lblSecurityInformarion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature:.
        /// </summary>
        internal static string lblSignature {
            get {
                return ResourceManager.GetString("lblSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string lblWelCome {
            get {
                return ResourceManager.GetString("lblWelCome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No forum.
        /// </summary>
        internal static string NoForum {
            get {
                return ResourceManager.GetString("NoForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items.
        /// </summary>
        internal static string NoItems {
            get {
                return ResourceManager.GetString("NoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not banned.
        /// </summary>
        internal static string NotBanned {
            get {
                return ResourceManager.GetString("NotBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not trusted.
        /// </summary>
        internal static string NotTrusted {
            get {
                return ResourceManager.GetString("NotTrusted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number forum views.
        /// </summary>
        internal static string NumberForumViews {
            get {
                return ResourceManager.GetString("NumberForumViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number thread views.
        /// </summary>
        internal static string NumberThreadViews {
            get {
                return ResourceManager.GetString("NumberThreadViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent post.
        /// </summary>
        internal static string ParentPost {
            get {
                return ResourceManager.GetString("ParentPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password field and the confirm password field must be equal.
        /// </summary>
        internal static string PasswordFieldAndTheConfirmPasswordFieldEqual {
            get {
                return ResourceManager.GetString("PasswordFieldAndTheConfirmPasswordFieldEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select forum.
        /// </summary>
        internal static string PleaseSelectForum {
            get {
                return ResourceManager.GetString("PleaseSelectForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select thread.
        /// </summary>
        internal static string PleaseSelectForumThread {
            get {
                return ResourceManager.GetString("PleaseSelectForumThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select post.
        /// </summary>
        internal static string PleaseSelectPost {
            get {
                return ResourceManager.GetString("PleaseSelectPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select user.
        /// </summary>
        internal static string PleaseSelectUser {
            get {
                return ResourceManager.GetString("PleaseSelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts.
        /// </summary>
        internal static string Posts {
            get {
                return ResourceManager.GetString("Posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts per page.
        /// </summary>
        internal static string PostsPerPage {
            get {
                return ResourceManager.GetString("PostsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Settings.
        /// </summary>
        internal static string ProfileSettings {
            get {
                return ResourceManager.GetString("ProfileSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        internal static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved post successfully.
        /// </summary>
        internal static string SavedPostSuccessfully {
            get {
                return ResourceManager.GetString("SavedPostSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SavePost {
            get {
                return ResourceManager.GetString("SavePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security user.
        /// </summary>
        internal static string SecurityUser {
            get {
                return ResourceManager.GetString("SecurityUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security user email.
        /// </summary>
        internal static string SecurityUserEmail {
            get {
                return ResourceManager.GetString("SecurityUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security user Id.
        /// </summary>
        internal static string SecurityUserID {
            get {
                return ResourceManager.GetString("SecurityUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        internal static string Signature {
            get {
                return ResourceManager.GetString("Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread.
        /// </summary>
        internal static string Thread {
            get {
                return ResourceManager.GetString("Thread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threads per page.
        /// </summary>
        internal static string ThreadsPerPage {
            get {
                return ResourceManager.GetString("ThreadsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread title.
        /// </summary>
        internal static string ThreadTitle {
            get {
                return ResourceManager.GetString("ThreadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total posts.
        /// </summary>
        internal static string TotalPosts {
            get {
                return ResourceManager.GetString("TotalPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total threads.
        /// </summary>
        internal static string TotalThreads {
            get {
                return ResourceManager.GetString("TotalThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trusted.
        /// </summary>
        internal static string Trusted {
            get {
                return ResourceManager.GetString("Trusted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User rate value.
        /// </summary>
        internal static string UserRateValue {
            get {
                return ResourceManager.GetString("UserRateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User type.
        /// </summary>
        internal static string UserType {
            get {
                return ResourceManager.GetString("UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please review the following field(s):.
        /// </summary>
        internal static string valSummHeader {
            get {
                return ResourceManager.GetString("valSummHeader", resourceCulture);
            }
        }
    }
}
