USE [eXMNouh]
GO
/****** Object:  Table [dbo].[Categories]    Script Date: 10/24/2011 22:36:13 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Categories](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](50) NOT NULL,
	[DESCRIPTION] [ntext] NOT NULL,
	[TYPE] [int] NOT NULL,
	[ATTRIBUTES] [nvarchar](50) NULL,
	[IS_DELETED] [bit] NOT NULL,
	[XSL_ID] [int] NULL,
	[Image] [nvarchar](50) NOT NULL,
	[LanguageID] [int] NULL,
	[Hash] [nvarchar](50) NULL,
 CONSTRAINT [PK_CATEGORY] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MenuItems]    Script Date: 10/24/2011 22:36:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MenuItems](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](50) NOT NULL,
	[DESCRIPTION] [ntext] NOT NULL,
	[DETAILS] [ntext] NOT NULL,
	[TYPE] [int] NOT NULL,
	[CATEGORY_ID] [int] NOT NULL,
	[URL] [ntext] NULL,
	[OrderNumber] [int] NOT NULL,
	[MenuID] [int] NOT NULL,
	[IMAGE] [ntext] NULL,
	[CREATION_DATE] [nvarchar](50) NOT NULL,
	[CREATED_BY] [nvarchar](50) NOT NULL,
	[CREATION_TIME] [nvarchar](50) NOT NULL,
	[PUBLISH_FROM] [nvarchar](50) NOT NULL,
	[PUBLISH_TO] [nvarchar](50) NOT NULL,
	[IS_DELETED] [bit] NOT NULL,
	[LanguageID] [int] NULL,
	[Ref_Lang_ID] [int] NULL,
 CONSTRAINT [PK_MenuItems] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  StoredProcedure [dbo].[usp_SelectMenuItemByLangandHash]    Script Date: 10/24/2011 22:36:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--region [dbo].[usp_SelectMenuItem]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Yahia using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectMenuItem]
-- Date Generated: 19 ÔÈÇØ, 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectMenuItemByLangandHash]
	@Hash nvarchar(50),
	@LanguageID int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[ID],
	[NAME],
	[DESCRIPTION],
	[DETAILS],
	[TYPE],
	[CATEGORY_ID],
	[URL],
	[OrderNumber],
	[MenuID],
	[IMAGE],
	[CREATION_DATE],
	[CREATED_BY],
	[CREATION_TIME],
	[PUBLISH_FROM],
	[PUBLISH_TO],
	[IS_DELETED],
	LanguageID,
	Ref_Lang_ID
FROM
	[dbo].[MenuItems]

WHERE
	CATEGORY_ID
	IN
	(
		SELECT ID FROM DBO.CATEGORIES
		WHERE	
		[Hash] = @Hash
		AND
		LanguageID = @LanguageID
	)	

--endregion
GO
/****** Object:  StoredProcedure [dbo].[usp_SelectMenuItemsPaged]    Script Date: 10/24/2011 22:36:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--region [dbo].[usp_SelectMenuItemsPaged]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Yahia using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectMenuItemsPaged]
-- Date Generated: 29 ßÇäæä ÇáËÇäí, 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectMenuItemsPaged]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[ID],
	[NAME],
	[DESCRIPTION],
	[DETAILS],
	[TYPE],
	[CATEGORY_ID],
	[URL],
	[OrderNumber],
	[MenuID],
	[IMAGE],
	[CREATION_DATE],
	[CREATED_BY],
	[CREATION_TIME],
	[PUBLISH_FROM],
	[PUBLISH_TO],
	[IS_DELETED],
	LanguageID,
	Ref_Lang_ID
FROM
	[dbo].[MenuItems]

--endregion
GO
/****** Object:  StoredProcedure [dbo].[usp_SelectMenuItem]    Script Date: 10/24/2011 22:36:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--region [dbo].[usp_SelectMenuItem]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Yahia using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectMenuItem]
-- Date Generated: 19 ÔÈÇØ, 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectMenuItem]
	@ID int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[ID],
	[NAME],
	[DESCRIPTION],
	[DETAILS],
	[TYPE],
	[CATEGORY_ID],
	[URL],
	[OrderNumber],
	[MenuID],
	[IMAGE],
	[CREATION_DATE],
	[CREATED_BY],
	[CREATION_TIME],
	[PUBLISH_FROM],
	[PUBLISH_TO],
	[IS_DELETED],
	LanguageID,
	Ref_Lang_ID
FROM
	[dbo].[MenuItems]
WHERE
	[ID] = @ID

--endregion
GO
/****** Object:  StoredProcedure [dbo].[usp_SelectMenuItemsAll]    Script Date: 10/24/2011 22:36:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--region [dbo].[usp_SelectMenuItemsAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Yahia using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectMenuItemsAll]
-- Date Generated: 19 ÔÈÇØ, 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectMenuItemsAll]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[ID],
	[NAME],
	[DESCRIPTION],
	[DETAILS],
	[TYPE],
	[CATEGORY_ID],
	[URL],
	[OrderNumber],
	[MenuID],
	[IMAGE],
	[CREATION_DATE],
	[CREATED_BY],
	[CREATION_TIME],
	[PUBLISH_FROM],
	[PUBLISH_TO],
	[IS_DELETED],
	LanguageId,
	Ref_Lang_ID
FROM
	[dbo].[MenuItems]
ORDER BY ORDERNUMBER

--endregion
GO
/****** Object:  StoredProcedure [dbo].[usp_SelectMenuItemasXml]    Script Date: 10/24/2011 22:36:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--region [dbo].[usp_SelectMenuItem]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Yahia using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectMenuItem]
-- Date Generated: 05 ÔÈÇØ, 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectMenuItemasXml]
	@ID int
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[ID],
	[NAME],
	[DESCRIPTION],
	[DETAILS],
	[TYPE],
	[CATEGORY_ID],
	[URL],
	[OrderNumber],
	[MenuID],
	[IMAGE],
	[CREATION_DATE],
	[CREATED_BY],
	[CREATION_TIME],
	[PUBLISH_FROM],
	[PUBLISH_TO],
	[IS_DELETED],
	LanguageID,
	Ref_Lang_ID
FROM
	[dbo].[MenuItems]
WHERE
	[ID] = @ID
for xml auto
--endregion
GO
/****** Object:  StoredProcedure [dbo].[usp_SelectMenuItemsSearch]    Script Date: 10/24/2011 22:36:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--region [dbo].[usp_SelectMenuItemsAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Yahia using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectMenuItemsAll]
-- Date Generated: 11 ÔÈÇØ, 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectMenuItemsSearch]
@KEYWORD nvarchar(50)
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[ID],
	[NAME],
	[DESCRIPTION],
	[DETAILS],
	[TYPE],
	[CATEGORY_ID],
	[URL],
	[OrderNumber],
	[MenuID],
	[IMAGE],
	[CREATION_DATE],
	[CREATED_BY],
	[CREATION_TIME],
	[PUBLISH_FROM],
	[PUBLISH_TO],
	[IS_DELETED],
	LanguageID,
	Ref_Lang_ID
FROM
	[dbo].[MenuItems]
WHERE 
	( (NAME='') OR (NAME LIKE '%'+@KEYWORD+'%') OR ([DESCRIPTION] LIKE '%'+@KEYWORD+'%') OR ([DETAILS] LIKE '%'+@KEYWORD+'%')) 
	
--endregion
GO
/****** Object:  StoredProcedure [dbo].[usp_SelectMenuItemsSearchPaging]    Script Date: 10/24/2011 22:36:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--region [dbo].[usp_SelectMenuItemsAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   Yahia using CodeSmith 4.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectMenuItemsAll]
-- Date Generated: 19 ÔÈÇØ, 2011
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectMenuItemsSearchPaging]
	@From int,
	@to int,
	@TotalRows int out,
	@Keyword nvarchar(50)
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED


SELECT
	[ID],
	[NAME],
	[DESCRIPTION],
	[DETAILS],
	[TYPE],
	[CATEGORY_ID],
	[URL],
	[OrderNumber],
	[MenuID],
	[IMAGE],
	[CREATION_DATE],
	[CREATED_BY],
	[CREATION_TIME],
	[PUBLISH_FROM],
	[PUBLISH_TO],
	[IS_DELETED],
	LanguageId,	
	Ref_Lang_ID
FROM
(
SELECT ROW_NUMBER() OVER (ORDER BY ORDERNUMBER) AS ROW,
	[ID],
	[NAME],
	[DESCRIPTION],
	[DETAILS],
	[TYPE],
	[CATEGORY_ID],
	[URL],
	[OrderNumber],
	[MenuID],
	[IMAGE],
	[CREATION_DATE],
	[CREATED_BY],
	[CREATION_TIME],
	[PUBLISH_FROM],
	[PUBLISH_TO],
	[IS_DELETED],
	LanguageId,
	Ref_Lang_ID
FROM
	[dbo].[MenuItems]
WHERE
	((@KEYWORD = '') OR ([NAME] like @KEYWORD) OR ([DETAILS] LIKE @KEYWORD))
)
AS ROWPAGING
WHERE 
ROW >= @FROM AND ROW <=@TO
	

SELECT @TotalRows = COUNT(*) FROM
	[dbo].[MenuItems]
WHERE
	((@KEYWORD = '') OR ([NAME] like @KEYWORD) OR ([DETAILS] LIKE @KEYWORD))
--endregion
GO
